services:
  sopwriter-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    environment:
      RESEND_API_KEY: ${RESEND_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
