services:
  sopwriter-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    environment:
      NEXT_PUBLIC_RESEND_API_KEY: ${NEXT_PUBLIC_RESEND_API_KEY}
      NEXT_PUBLIC_OPENAI_API_KEY: ${NEXT_PUBLIC_OPENAI_API_KEY}
